---
title: "linear_models"
author: "zhuolun"
date: "11/16/2021"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)

```


```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) + geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

let's look at this
```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

```{r}
fit %>% 
  broom::glance()
```

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  knitr::kable(digits = 3)
```

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = resid)) + geom_density() + xlim(-200, 200)
```

let's fit a different model 

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * borough + room_type * borough, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb %>% 
  relocate(borough) %>%
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(prices = stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(borough, lm_results) %>% 
  unnest(lm.results) %>% 
  filter(term = )
```

```{r}
nest_lm_res %>% 
  select(borough, term, estimate) %>% 
  mutate(term = fct_inorder(term)) %>% 
  pivot_wider(
    names_from = term, values_from = estimate) %>% 
  knitr::kable(digits = 3)
```

```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(borough == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results)
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(borough) %>% 
  relocate(neighbourhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price = stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
      
  ) %>% 
  select(neighbourhood, lm_results) %>% 
  unnest(lm_results)
```

```{r}

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

